<?php
/*
 * Plugin class
 *
 * auto-generated by the sfDoctrine plugin
 * creation date: 2007-05-02 13:45:58
 */
abstract class PlugincsSetting extends BasecsSetting
{
  public function getOption($name, $required = false)
  {
    sfProjectConfiguration::getActive()->loadHelpers(array('Tag'));
    $config = _parse_attributes($this->getOptions());
    
    if ($required && !isset($config[$name])) 
    {
      throw new sfException(sprintf('Missing required option "%s" in setting %s', $name, $this['name']));
    }
    
    return isset($config[$name]) ? $config[$name] : false;
  }
  
  public function getOptionsArray()
  {
    sfProjectConfiguration::getActive()->loadHelpers(array('Tag'));
    return _parse_attributes($this->getOptions());
  }
  
  public function getUploadPath()
  {
    if ($this['type'] != 'upload') 
    {
      throw new sfException(sprintf('Cannot get Upload Path for setting of type "%s"', $this['type']));
    }
    
    $default_path = csSettings::getDefaultUploadPath();
        
    $target_path = $this->getOption('upload_path');
    
    return $target_path ? $target_path : $default_path;
  }
  public function getGroup()
  {
    return $this['setting_group'];
  }
  
  // remove cache when an item is updated
  public function postSave($event)
  {
    csSettings::clearSettingsCache();
  }
  
  public function postDelete($event)
  {
    csSettings::clearSettingsCache();
  }
}
