<?php
/*
 * Plugin class
 *
 * auto-generated by the sfDoctrine plugin
 * creation date: 2007-05-02 13:45:58
 */
abstract class PlugincsSetting extends BasecsSetting
{
  public function getOption($name, $required = false)
  {
    sfProjectConfiguration::getActive()->loadHelpers(array('Tag'));
    $config = _parse_attributes($this->getOptions());
    
    if ($required && !isset($config[$name])) 
    {
      throw new sfException(sprintf('Missing required option "%s" in setting %s', $name, $this['name']));
    }
    
    return isset($config[$name]) ? $config[$name] : false;
  }
}
