all:
  csSettingsPlugin:
    types:      
      input:        Text Field
      textarea:     Text Area
      checkbox:     Checkbox
      select:       Select List
      yesno:        Yes/No Radios
      model:        Database Model
      upload:       Upload
    authMethod:     isAuthenticated   #used to determine when seo admin bar is visible
    tableMethod:    findAll           #used to pull the list of settings
    cachepaths:                       #override the cache path, for whatever reason you might want to
      settings_array: cs_settings.settings_array.cache
      object_array:   cs_settings.obj_array.cache