---
csSetting:
  actAs: [Sluggable]
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
    type:
      type: string(255)
    options:
      type: string
    value:
      type: clob